

INSERT INTO category (NAME) SELECT 'Monitor' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM category WHERE NAME='Monitor');
INSERT INTO category (NAME) SELECT 'Keyboard' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM category WHERE NAME='Keyboard');
INSERT INTO category (NAME) SELECT 'Mouse' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM category WHERE NAME='Mouse');


INSERT INTO product (CATID, NAME, PRICE) SELECT A.ID, 'Dell', 2000.99 FROM category A WHERE A.NAME='Monitor' AND NOT EXISTS (SELECT 1 FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Monitor' AND B.NAME='Dell');
INSERT INTO product (CATID, NAME, PRICE) SELECT A.ID, 'Apple', 3000.00 FROM category A WHERE A.NAME='Monitor' AND NOT EXISTS (SELECT 1 FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Monitor' AND B.NAME='Apple');
INSERT INTO product (CATID, NAME, PRICE) SELECT A.ID, 'Logitech', 50.00 FROM category A WHERE A.NAME='Keyboard' AND NOT EXISTS (SELECT 1 FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Keyboard' AND B.NAME='Logitech');
INSERT INTO product (CATID, NAME, PRICE) SELECT A.ID, 'Logitech', 20.15 FROM category A WHERE A.NAME='Mouse' AND NOT EXISTS (SELECT 1 FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Mouse' AND B.NAME='Logitech');
INSERT INTO product (CATID, NAME, PRICE) SELECT A.ID, 'HP', 20.15 FROM category A WHERE A.NAME='Mouse' AND NOT EXISTS (SELECT 1 FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Mouse' AND B.NAME='HP');


INSERT INTO orders (PRDID, CNT, PHONE) SELECT B.ID, 1, '0400100101' FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Monitor' AND B.NAME='Dell' AND NOT EXISTS (SELECT 1 FROM category A, product B, orders C WHERE A.ID=B.CATID AND B.ID=C.PRDID AND A.NAME='Monitor' AND B.NAME='Dell' AND C.PHONE='0400100101');
INSERT INTO orders (PRDID, CNT, PHONE) SELECT B.ID, 2, '0400100102' FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Monitor' AND B.NAME='Apple' AND NOT EXISTS (SELECT 1 FROM category A, product B, orders C WHERE A.ID=B.CATID AND B.ID=C.PRDID AND A.NAME='Monitor' AND B.NAME='Apple' AND C.PHONE='0400100102');
INSERT INTO orders (PRDID, CNT, PHONE) SELECT B.ID, 2, '0400100103' FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Keyboard' AND B.NAME='Logitech' AND NOT EXISTS (SELECT 1 FROM category A, product B, orders C WHERE A.ID=B.CATID AND B.ID=C.PRDID AND A.NAME='Keyboard' AND B.NAME='Logitech' AND C.PHONE='0400100103');
INSERT INTO orders (PRDID, CNT, PHONE) SELECT B.ID, 1, '0400100104' FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Mouse' AND B.NAME='Logitech' AND NOT EXISTS (SELECT 1 FROM category A, product B, orders C WHERE A.ID=B.CATID AND B.ID=C.PRDID AND A.NAME='Mouse' AND B.NAME='Logitech' AND C.PHONE='0400100104');
INSERT INTO orders (PRDID, CNT, PHONE) SELECT B.ID, 2, '0400100105' FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Mouse' AND B.NAME='HP' AND NOT EXISTS (SELECT 1 FROM category A, product B, orders C WHERE A.ID=B.CATID AND B.ID=C.PRDID AND A.NAME='Mouse' AND B.NAME='HP' AND C.PHONE='0400100105');
INSERT INTO orders (PRDID, CNT, PHONE) SELECT B.ID, 1, '0499887116' FROM category A, product B WHERE A.ID=B.CATID AND A.NAME='Mouse' AND B.NAME='HP' AND NOT EXISTS (SELECT 1 FROM category A, product B, orders C WHERE A.ID=B.CATID AND B.ID=C.PRDID AND A.NAME='Mouse' AND B.NAME='HP' AND C.PHONE='0499887116');
